In [27]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from astropy.time import Time 

In [28]:
astname = '2010fh81'
fname = f'time_{astname}.txt'
rawdata = pd.read_csv(fname)
len(rawdata)

41

In [29]:
time_tdb = []
time_utc = []
for i in range(len(rawdata)):
    ti = Time(rawdata['mjd'][i],format='mjd',scale='utc')
    time_tdb.append(ti.tdb.jd)
    time_utc.append(ti.utc.jd)

In [30]:
tt = np.array(time_tdb[:15])
np.savetxt(f'{astname}_tdb_time.txt',tt,fmt='%.6f')
tt2 = np.array(time_utc[:15])
np.savetxt(f'{astname}_utc_time.txt',tt2,fmt='%.6f')

In [44]:
import numpy as np
name = 'sunutc'
f = open(name+'.txt',"r")
lines = f.readlines()
i=0
mpcdata = []
for line in lines:
    if (i%4 == 1): 
        mpcdata.append(line.split())
    i+=1
f.close()
mpcdata = np.float64(mpcdata)
np.savetxt('new'+name+'.txt',mpcdata)

In [45]:
au = 149597870700.0
ssb = np.loadtxt('newssb.txt')
sun = np.loadtxt('newsun.txt')
newsun = np.loadtxt('newsunutc.txt')
delta = (ssb-sun)*au
print(ssb)
print(sun)
print(ssb-sun)
print(delta/1000)

[[-0.99475007 -0.1499398   0.29340003]
 [-0.99409356 -0.15221983  0.29313891]
 [-0.99343256 -0.15449916  0.29287646]
 [-0.99276704 -0.15677777  0.29261268]
 [-0.99243162 -0.15792011  0.2924799 ]
 [-0.99209701 -0.15905568  0.29234756]
 [-0.99175933 -0.16019763  0.29221412]
 [-0.99142247 -0.16133283  0.29208111]
 [-0.99142183 -0.16133501  0.29208085]
 [-0.99108253 -0.16247441  0.29194699]
 [-0.99040122 -0.16475043  0.29167854]
 [-0.99040057 -0.16475262  0.29167828]
 [-0.99005921 -0.16588706  0.29154394]
 [-0.98971474 -0.16702788  0.29140848]
 [-0.98937113 -0.16816193  0.29127348]]
[[-0.99077495 -0.15235753  0.29339014]
 [-0.99011816 -0.15463679  0.29312902]
 [-0.98945688 -0.15691534  0.29286657]
 [-0.98879108 -0.15919317  0.29260278]
 [-0.98845552 -0.16033512  0.29247   ]
 [-0.98812078 -0.1614703   0.29233765]
 [-0.98778296 -0.16261186  0.2922042 ]
 [-0.98744596 -0.16374667  0.29207119]
 [-0.98744531 -0.16374886  0.29207093]
 [-0.98710588 -0.16488786  0.29193707]
 [-0.98642429 -0.1671631

In [47]:
print(sun)
print(newsun)
print((sun-newsun)*au/1000)

[[-0.99077495 -0.15235753  0.29339014]
 [-0.99011816 -0.15463679  0.29312902]
 [-0.98945688 -0.15691534  0.29286657]
 [-0.98879108 -0.15919317  0.29260278]
 [-0.98845552 -0.16033512  0.29247   ]
 [-0.98812078 -0.1614703   0.29233765]
 [-0.98778296 -0.16261186  0.2922042 ]
 [-0.98744596 -0.16374667  0.29207119]
 [-0.98744531 -0.16374886  0.29207093]
 [-0.98710588 -0.16488786  0.29193707]
 [-0.98642429 -0.16716311  0.29166861]
 [-0.98642364 -0.16716529  0.29166835]
 [-0.98608214 -0.16829934  0.29153401]
 [-0.98573753 -0.16943977  0.29139855]
 [-0.98539378 -0.17057344  0.29126354]]
[[-0.99077874 -0.15234433  0.29339165]
 [-0.99012198 -0.15462359  0.29313054]
 [-0.98946072 -0.15690215  0.29286809]
 [-0.98879495 -0.15917999  0.29260431]
 [-0.9884594  -0.16032194  0.29247153]
 [-0.98812467 -0.16145712  0.29233919]
 [-0.98778687 -0.16259868  0.29220575]
 [-0.98744988 -0.16373349  0.29207274]
 [-0.98744923 -0.16373568  0.29207248]
 [-0.98710982 -0.16487469  0.29193862]
 [-0.98642825 -0.1671499